import type { Metadata, Viewport } from "next";
import "./globals.css";
import { Navbar } from "./navbar";
import AuthProvider from "./lib/utils/authContext";
import { DataStoreProvider } from "./lib/data-store/store";
import { WindowProvider } from "./lib/utils/windowContext";
import { InfoBar } from "./components/info-bar";
import { Toaster } from "react-hot-toast";
import { Poppins } from "next/font/google";
// import { CartProvider } from "./lib/cart/cartContext";

const poppins = Poppins({
  weight: '400',
  style: 'normal',
  subsets: ['latin'],
  display: 'swap',
  preload: true,
  adjustFontFallback: true,
  fallback: ['sans-serif'],
  variable: '--font-poppins'
});

export const metadata: Metadata = {
  title: "Blackinkpaper Shop",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: "#000000",
  initialScale: 1,
  width: "device-width",
  maximumScale: 1,
  userScalable: false,
  colorScheme: "dark light",
  viewportFit: 'cover',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <DataStoreProvider>
          <WindowProvider>
            <body
              className={`${poppins.className} `}
            >
              <Toaster />

              <Navbar />
              {/* <NavigationBar /> */}
              <InfoBar />
              <main className="overflow-x-hidden">
                {children}
              </main>
            </body>
          </WindowProvider>
        </DataStoreProvider>
      </AuthProvider>

    </html>
  );
}
