import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "./navbar";
import AuthProvider from "./lib/utils/authContext";
import { DataStoreProvider } from "./lib/data-store/store";
import { WindowProvider } from "./lib/utils/windowContext";
import { InfoBar } from "./components/info-bar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Blackinkpaper Shop",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: "#000000",
  initialScale: 1,
  width: "device-width",
  maximumScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <DataStoreProvider>
          <WindowProvider>
            <body
              className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
              <Navbar />
              <InfoBar />
              <main className="min-w-screen overflow-hidden">
                {children}
              </main>
            </body>
          </WindowProvider>
        </DataStoreProvider>
      </AuthProvider>

    </html>
  );
}
